export const team = [
  {
    name: "Eduardo Inoa",
    slug: "eduardo-inoa",
    role: "CEO & Co-Founder",
    specialties: [
      "Real Estate",
      "Tax Services",
      "Business Consulting",
      "Notary",
      "DR Investments",
    ],
    bio: "Eduardo leads Optima with a unique combination of real estate expertise, tax knowledge, financial experience, and strategic marketing. He focuses on delivering clarity, transparency, and high-quality solutions tailored to each client.",
    photo: "/images/team/eduardo.jpg",
    email: "eduardo@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
  {
    name: "Ader Melenciano",
    slug: "ader-melenciano",
    role: "COO & Co-Founder",
    specialties: [
      "Operations",
      "Client Experience",
      "Service Coordination",
      "Compliance",
    ],
    bio: "Ader oversees operations and ensures every service runs smoothly. With a strong attention to detail and systems management, he maintains the high standards that define Optima.",
    photo: "/images/team/ader.jpg",
    email: "ader@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
  {
    name: "Carlos Lizardo",
    slug: "carlos-lizardo",
    role: "Senior Tax Specialist",
    specialties: [
      "Personal Taxes",
      "Business Filings",
      "ITIN",
      "Bookkeeping Support",
    ],
    bio: "Carlos provides reliable and accurate tax assistance for individuals and business owners, ensuring each client receives clear guidance and compliant filings.",
    photo: "/images/team/carlos.jpg",
    email: "carlos@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
  {
    name: "Adalis Balbuena",
    slug: "adalis-balbuena",
    role: "Immigration Form Preparer",
    specialties: [
      "USCIS Forms",
      "Family Petitions",
      "DACA",
      "FOIA",
      "Renewals",
    ],
    bio: "Adalis supports clients with immigration form preparation, offering clear assistance and careful document handling for families navigating important processes. (Non-attorney service)",
    photo: "/images/team/adalis.jpg",
    email: "adalis@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
  {
    name: "Jadelyn Jiménez",
    slug: "jadelyn-jimenez",
    role: "Client Services Coordinator",
    specialties: [
      "Communication",
      "Scheduling",
      "Lead Intake",
      "Support",
    ],
    bio: "Jadelyn is the main point of contact for clients, ensuring quick responses, organized appointments, and a smooth service experience.",
    photo: "/images/team/jadelyn.jpg",
    email: "jadelyn@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
  {
    name: "Belysa Inoa",
    slug: "belysa-inoa",
    role: "Service Support Specialist",
    specialties: [
      "Client Assistance",
      "Documentation Support",
      "Customer Care",
    ],
    bio: "Belysa helps clients throughout the process with reliable support, clear communication, and organized follow-through.",
    photo: "/images/team/belysa.jpg",
    email: "belysa@optimaservicegroup.com",
    phone: "+1 (978) 705-5509",
  },
];

export type TeamMember = typeof team[0];
